#+BEGIN_COMMENT
.. title: FX Series - Intro
.. slug: fx-series-intro
.. date: 2021-10-08 03:35:52 UTC-04:00
.. tags: Finance, FX
.. category: Finance, FX
.. link: 
.. description: 
.. type: text

#+END_COMMENT


This is the start of a series on FX, the goal is to have a top down approach of this asset class, starting with the History, structure and economy of this asset class, then later dive down the diffrerent instruments and strategies.

* Introduction
  Foreign Exchange is by far the largest market in the world, with an estimated $6.6 trillion average daily turnover (as of 2019). It is distinguished from the commodity or equity maarket by having no fixed base, it is not located in a building and is not limited by fixed trading hours.
  A Foreign Exchange transaction is a contract to exchange one currency foor another currency at an agreed rate on an agreed date.

  The first forward foreign exchange transactions can be traced back to the money-changers in Lombardy in the 1500s. Foreign exchange, as we know it today, has its roots in the gold standard, which was introduced in 1880. It was a system of fixed exchange rates in relation to gold and the absence of any exchange control.

  Banking and financial markets closer to those of today were started in the coffee houses of European financial centers, such as the City of London. In the seventeenth century these cofee houses became ther meeting places not only of merchants seeking to trade their finished goods, but also of those who brought and sold solely for profit. It was the City of London's domination of these early markets that saw it maturing through the powerful late Victorian era, and it was strong enough to survive two world wars and the depression of the 1930s.

** Spot, Forward and more

   A Spot transaction is where the delivery  of the currency is two business days from trade date (except the canadian dollar, which is one day).
   A Forward transaction is any transaction that settles on a date beyond spot.
   A Currency future obligates its owner to purchase a specified asset at a specified exercise price on the contract maturity date.
   An option gives the owner the right but not the obligation to buy annd sell a specified quantity of a currency at a specified rate on or before a specified date.
   A foreign currency swap is where two currencies a exchanged for an agreed period of time annd re-exchanged at maturity at the same exchange rate.

* Reference 
Shamah, S. 2008. A Foreign Exchange Primer.
